"""
PostgreSQL Migration Script

Usage:
    python scripts/migrate_to_postgres.py

This script exports data from SQLite and generates PostgreSQL-compatible SQL.
Run after setting DATABASE_URL=postgresql://...
"""

import sqlite3
import json
import os
import sys

DATABASE_FILE = "madhav_crm.db"

def export_sqlite_data():
    """Export all data from SQLite to JSON"""
    conn = sqlite3.connect(DATABASE_FILE)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    tables = [
        "orders", "users", "api_keys", "page_events", "activity_log",
        "login_history", "order_notes", "order_assignments",
        "document_versions", "refunds", "coupons", "notifications",
        "invoices", "saved_drafts"
    ]
    data = {}
    for table in tables:
        try:
            cursor.execute(f"SELECT * FROM {table}")
            rows = [dict(r) for r in cursor.fetchall()]
            if rows:
                data[table] = rows
                print(f"  {table}: {len(rows)} rows")
        except Exception:
            print(f"  {table}: skipped (not found)")
    conn.close()
    return data

def generate_postgres_schema():
    return """
-- PostgreSQL Schema for Instadeed
-- Generated by migration script

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    customer_name TEXT,
    customer_phone TEXT,
    customer_email TEXT,
    agreement_type TEXT,
    source TEXT,
    status TEXT,
    amount REAL,
    form_data JSONB,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    cloud_url TEXT,
    leegality_doc_id TEXT,
    leegality_sign_url TEXT,
    is_favorite INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    phone TEXT DEFAULT '',
    location TEXT DEFAULT '',
    device_info TEXT DEFAULT '',
    role TEXT DEFAULT 'user',
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP,
    last_login TIMESTAMP
);

-- ... (remaining tables use same pattern)

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(customer_phone);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
"""

def main():
    print("Exporting SQLite data...")
    data = export_sqlite_data()
    output_file = "migrations/postgres_seed.json"
    with open(output_file, "w") as f:
        json.dump(data, f, indent=2, default=str)
    print(f"\nData exported to {output_file}")
    print("\nPostgreSQL Schema:")
    print(generate_postgres_schema())
    print("\nTo complete migration:")
    print("1. Create PostgreSQL database and run the schema above")
    print("2. Set DATABASE_URL=postgresql://... in .env")
    print("3. Load data from migrations/postgres_seed.json")
    print("4. Update server.py to use psycopg2 for DB access")

if __name__ == "__main__":
    main()
